stages:
  - lint

backend_lint:
  stage: lint
  image: bitnami/laravel:latest
  script:
    - cd ./backend
    - cd ./tools/php-cs-fixer
    - composer install
    - cd ../../
    - ./tools/php-cs-fixer/vendor/bin/php-cs-fixer fix -vvv --dry-run --config=tools/php-cs-fixer/.php-cs-fixer.dist.php --stop-on-violation --using-cache=no

frontend_lint:
  stage: lint
  image: node:16
  cache:
    paths:
      - frontend/.npm/
    key:
      files:
        - frontend/package-lock.json
  script:
    - cd ./frontend
    - npm ci --cache .npm --prefer-offline
    - npm run lint
